basePath: /
definitions:
  cows.cowsFilter:
    properties:
      birkingDateFrom:
        description: date field
        example: "1800-01-21"
        type: string
      birkingDateTo:
        description: date field
        example: "2800-01-21"
        type: string
      birthDateFrom:
        description: used
        example: "1800-01-21"
        type: string
      birthDateTo:
        description: used
        example: "2800-01-21"
        type: string
      breedId:
        description: used
        items:
          type: integer
        type: array
      calvingDateFrom:
        description: used
        example: "1800-01-21"
        type: string
      calvingDateTo:
        description: used
        example: "2800-01-21"
        type: string
      controlMilkingDateFrom:
        description: used
        example: "1800-01-21"
        type: string
      controlMilkingDateTo:
        description: used
        example: "2800-01-21"
        type: string
      departDateFrom:
        description: used
        example: "1800-01-21"
        type: string
      departDateTo:
        description: used
        example: "2800-01-21"
        type: string
      entitiesOnPage:
        default: 50
        description: used
        type: integer
      exterior:
        default: 3.14
        description: used
        type: number
      farmID:
        default: 1
        description: used
        type: integer
      genotypingDateFrom:
        description: ??? Genotiping needed
        example: "1800-01-21"
        type: string
      genotypingDateTo:
        description: ??? Genotiping needed
        example: "2800-01-21"
        type: string
      inbrindingCoeffByFamilyFrom:
        default: 3.14
        description: used
        type: number
      inbrindingCoeffByFamilyTo:
        default: 3.14
        description: used
        type: number
      inbrindingCoeffByFenotypeFrom:
        default: 3.14
        description: ??? Genotiping needed
        type: number
      inbrindingCoeffByFenotypeTo:
        default: 3.14
        description: ??? Genotiping needed
        type: number
      inseminationDateFrom:
        example: "1800-01-21"
        type: string
      inseminationDateTo:
        example: "2800-01-21"
        type: string
      isAborted:
        default: false
        description: used
        type: boolean
      isDead:
        default: false
        description: used
        type: boolean
      isIll:
        default: false
        description: ??? Genotiping needed
        type: boolean
      isStillBorn:
        default: false
        description: used
        type: boolean
      isTwins:
        default: false
        description: used
        type: boolean
      monogeneticIllneses:
        description: ??? Genotiping needed
        items:
          type: integer
        type: array
      pageNumber:
        default: 1
        description: used
        type: integer
      searchQuery:
        description: used
        example: Буренка
        type: string
      sex:
        description: used
        items:
          type: integer
        type: array
    type: object
  models.Breed:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
  models.CheckMilk:
    properties:
      checkDate:
        type: string
      fat:
        type: integer
      id:
        type: integer
      lactationId:
        type: integer
      milk:
        type: integer
      protein:
        type: integer
    type: object
  models.Cow:
    properties:
      approved:
        description: int to load database dump
        type: integer
      birkingDate:
        type: string
      birthDate:
        type: string
      breed:
        $ref: '#/definitions/models.Breed'
      breedId:
        type: integer
      createdAt:
        type: string
      deathDate:
        type: string
      departDate:
        type: string
      exterior:
        type: number
      farm:
        $ref: '#/definitions/models.Farm'
      farmGroup:
        $ref: '#/definitions/models.Farm'
      farmGroupId:
        type: integer
      farmID:
        type: integer
      father:
        $ref: '#/definitions/models.Cow'
      fatherId:
        type: integer
      id:
        type: integer
      identificationNumber:
        type: string
      inbrindingCoeffByFamily:
        type: number
      inventoryNumber:
        type: string
      isDead:
        type: boolean
      lactation:
        items:
          $ref: '#/definitions/models.Lactation'
        type: array
      mother:
        $ref: '#/definitions/models.Cow'
      motherId:
        type: integer
      name:
        type: string
      rshnnumber:
        type: string
      selecsNumber:
        type: string
      sex:
        $ref: '#/definitions/models.Sex'
      sexId:
        type: integer
    type: object
  models.DailyMilk:
    properties:
      date:
        type: string
      fat:
        type: integer
      fatEvening:
        type: integer
      fatMorning:
        type: integer
      fatNoon:
        type: integer
      id:
        type: integer
      lactationId:
        type: integer
      milk:
        type: integer
      milkEvening:
        type: integer
      milkMorning:
        type: integer
      milkNoon:
        type: integer
      protein:
        type: integer
      proteinEvening:
        type: integer
      proteinMorning:
        type: integer
      proteinNoon:
        type: integer
    type: object
  models.District:
    properties:
      id:
        type: integer
      name:
        type: string
      region:
        $ref: '#/definitions/models.Region'
      regionId:
        type: integer
    type: object
  models.Farm:
    properties:
      address:
        type: string
      cowsCount:
        type: integer
      description:
        type: string
      district:
        $ref: '#/definitions/models.District'
      districtId:
        type: integer
      email:
        type: string
      id:
        type: integer
      inn:
        type: string
      name:
        type: string
      nameShort:
        type: string
      parrent:
        $ref: '#/definitions/models.Farm'
      parrentId:
        type: integer
      phone:
        type: string
      region:
        $ref: '#/definitions/models.Region'
      regionId:
        type: integer
      type:
        type: integer
    type: object
  models.Lactation:
    properties:
      abort:
        type: boolean
      calvingCount:
        type: integer
      calvingDate:
        type: string
      checkMilks:
        items:
          $ref: '#/definitions/models.CheckMilk'
        type: array
      cowId:
        type: integer
      dailyMilks:
        items:
          $ref: '#/definitions/models.DailyMilk'
        type: array
      date:
        type: string
      days:
        type: integer
      fat305:
        type: integer
      fatAll:
        type: integer
      id:
        type: integer
      insemenationDate:
        type: string
      insemenationNum:
        type: integer
      milk305:
        type: integer
      milkAll:
        type: integer
      number:
        type: integer
      protein305:
        type: integer
      proteinAll:
        type: integer
    type: object
  models.Region:
    properties:
      id:
        default: 1
        type: integer
      name:
        example: Усть-Каменский
        type: string
    type: object
  models.Sex:
    properties:
      id:
        type: integer
      name:
        type: string
    type: object
externalDocs:
  description: OpenAPI
  url: https://swagger.io/resources/open-api/
host: 83.69.248.180:8080
info:
  contact:
    email: support@swagger.io
    name: API Support
    url: http://www.swagger.io/support
  description: This is a sample server celler server.
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  termsOfService: http://swagger.io/terms/
  title: GenMilk API
  version: "1.0"
paths:
  /breeds/get:
    get:
      description: |-
        Get list of breeds.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Breed'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of breeds
      tags:
      - Breeds
  /checkMilks/get:
    get:
      description: |-
        Get list of CheckMilks.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.CheckMilk'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of checkMilks
      tags:
      - CheckMilks
  /cows/filter:
    post:
      consumes:
      - application/json
      description: |-
        Get filtered list of cows.
        SearchQuery - имя, номер РСХН или инвентарный номер
        PageNumber - номер страницы для отображения
        EntitiesOnPage - количество коров на каждой странице
        Sex - массив полов для поиска (можно выбрать несколько)
        FarmID - ID фермы на которой живет корова
        BirthDateFrom - Отображает коров, родившихся после этой даты
        BirthDateTo - Отображает коров, родившихся до этой даты
        IsDead - Если флаг истина - ищет мертвых коров, иначе живых
        DepartDateFrom - Ищет коров отбывших из коровника после данной даты
        DepartDateTo - Ищет коров отбывших из коровника до данной даты
        BreedId - ищет коров имеющих одну из пород по BreedId
        GenotypingDateFrom - НЕ ИСПОЛЬЗУЕТСЯ
        GenotypingDateTo - НЕ ИСПОЛЬЗУЕТСЯ
        ControlMilkingDateFrom - ищет коров у которых была хотябы одна контрольная дойка после этой даты
        ControlMilkingDateTo - ищет коров у которых была хотябы одна контрольная дойка до этой даты

        Exterior - Ищет коров с оценкой экстерьера равной этому значению
        InseminationDateFrom - Ищет коров которые были хотябы раз осеменены после данной даты
        InseminationDateTo - Ищет коров которые были хотябы раз осеменены до данной даты
        CalvingDateFrom  - Ищет коров у которых был отел хотябы раз после данной даты
        CalvingDateTo - Ищет коров у которых был отел хотябы раз до данной даты
        IsStillBorn  - Ищет коров у которых хотябы раз было мертворождение
        IsTwins - Ищет коров у которых хотябы раз родились близнецы/двойняшки
        IsAborted - Ищет коров, которым хотябы раз сделали аборт
        IsIll - НЕ ИСОПЛЬЗУЕТСЯ
        BirkingDateFrom - Ищет коров у которых дата перебирковки больше
        BirkingDateTo - Ищет коров у которых дата перебирковки меньше

        InbrindingCoeffByFamilyFrom Ищет коров, у которых коэф. инбриндинга по роду больше
        InbrindingCoeffByFamilyTo   - Ищет коров у которых дата перебирковки меньше

        InbrindingCoeffByFenotypeFrom Genotiping needed
        InbrindingCoeffByFenotypeTo    Genotiping needed

        MonogeneticIllneses []uint Genotiping needed
      parameters:
      - description: applied filters
        in: body
        name: filter
        required: true
        schema:
          $ref: '#/definitions/cows.cowsFilter'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cow'
            type: array
        "422":
          description: Unprocessable Entity
          schema:
            additionalProperties: {}
            type: object
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get filtered list of cows
      tags:
      - Cows
  /cows/get:
    get:
      description: |-
        Get list of farms.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Cow'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of farms
      tags:
      - Cows
  /dailyMilks/get:
    get:
      description: |-
        Get list of DailyMilks.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.DailyMilk'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of DailyMilks
      tags:
      - DailyMilks
  /districts/get:
    get:
      description: |-
        Get list of Districts.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.DailyMilk'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of Districts
      tags:
      - Districtts
  /farms/get:
    get:
      description: |-
        Get list of farms.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Farm'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of farms
      tags:
      - Farms
  /lactations/get:
    get:
      description: |-
        Get list of farms.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Lactation'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of farms
      tags:
      - Lactations
  /regions/get:
    get:
      description: Get list of regions.
      parameters:
      - description: id of region to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Region'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of regions
      tags:
      - Regions
  /sexes/get:
    get:
      description: |-
        Get list of breeds.
        DOES NOT RETURN SUBOBJECTS
      parameters:
      - description: id of farm to return
        in: query
        name: id
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.Sex'
            type: array
        "500":
          description: Internal Server Error
          schema:
            additionalProperties: {}
            type: object
      summary: Get list of breeds
      tags:
      - Sexes
securityDefinitions:
  BasicAuth:
    type: basic
swagger: "2.0"
